#!/usr/bin/env bash

set -e

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /var/www/html/vendor ]; then
    cd /var/www/html
    composer install --no-interaction --prefer-dist --optimize-autoloader
fi

exec /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf



